### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by fran6co** [triton-inference-server/dali_backend#142]
When running this pipeline it complains it can't find numpy:

```
import nvidia.dali as dali
import nvidia.dali.types as types
from nvidia.dali.plugin.triton import autoserialize
import numpy as np


@autoserialize
@dali.pipeline_def(batch_size=3, num_threads=1, device_id=0)
def pipe():
    max_size = 896
    fill_value = 114.0/255

    images = dali.fn.external_source(device="gpu", name="images")
    images = dali.fn.crop_mirror_normalize(images, output_layout=types.NCHW, scale=1.0/255, dtype=types.FLOAT)
    images = dali.fn.resize(images, max_size=max_size, mode="not_larger")

    shapes = dali.fn.shapes(images, dtype=types.INT64)

    w = dali.fn.slice(shapes, 2, 1, axes=[0])
    h = dali.fn.slice(shapes, 1, 1, axes=[0])

    dx = dali.fn.cast((max_size - w) // 2, dtype=types.FLOAT)
    dy = dali.fn.cast((max_size - h) // 2, dtype=types.FLOAT)

    shift = dali.fn.stack(dx, dy, 0.0, axis=0)
    transform = dali.fn.cat(np.identity(3, dtype=np.float32), shift, axis=1)

    letterboxed = dali.fn.warp_affine(images, transform, size=[max_size, max_size], fill_value=fill_value, interp_type=types.INTERP_LINEAR)
    
    return letterboxed
```

**Comment by jantonguirao** [comment]
In those examples, numpy is used to produce some kind of data to be used together with the DALI pipeline. However, DALI doesn't need numpy to work and therefore, adding it to its dependencies would be in my opinion wrong.

**Comment by fran6co** [comment]
What if you need to build a transformation matrix just like I'm showing in the example code? That's a very normal thing to do and I don't see the downside of adding numpy to the env

**Comment by fran6co** [comment]
I don't agree about that this is equivalent to CuPy or Torch. I created this issue not as just "DALI supports X then this backend should as well" but with a specific use case. Can you advice how would you solve it without numpy?

**Comment by jantonguirao** [comment]
@fran6co 
> Can you advice how would you solve it without numpy?

Yes. You can achieve that like this:
```
identity_mat = fn.constant(shape=(3, 3), fdata=[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0], dtype=types.FLOAT, device="cpu")
```

**Comment by fran6co** [comment]
@jantonguirao thanks, I will try that

**Comment by jantonguirao** [comment]
If this is a question to install numpy in the environment of the DALI backend, then I think that it'd be a good idea for convenience. My original comment was about adding numpy as a dependency to DALI, which would not make sense.

**Comment by fran6co** [comment]
The PR is to add numpy to the backend unless I added it to the wrong place

**Comment by szalpal** [comment]
The original issue here was to create an auxiliary matrix using numpy. @fran6co proposed to extend DALI Backend dependencies with `numpy`. However, there is a solution to this issue without the need of introducing an extra dependency and therefore is preferable. Thus I'll close this issue.

Nevertheless, the question of adding more dependencies to DALI Backend is still a valid one. On one hand, there certainly are use cases, where such dependency would make development the inference solution way easier. On the other, such approach looks like a gift that will keep giving: there will always be an extra dependency to add. For the latter reason I believe that adding those in a way presented in #143 is not the wanted solution (although numpy is so popular, that we may end up with this). Instead, I believe there should be an easy-ish way to add any particular dependency to the deployed `tritonserver` image. We'll put this to our backlog and we'll design something proper.
