### ISSUE TITLE
How to format client code for inception example

### ISSUE THREAD

**Issue by bitchaser12** [triton-inference-server/dali_backend#237]
I'm trying to make a dali preprocessing pipeline extremely similar to the inception example but I can't seem to figure out how to get the correct format on the client side. Here is the code I have now on the client side:

```
def prepare_batches(data_loader):
    batches = []
    for dataiter in data_loader:
        images, labels = dataiter['image'], dataiter['label']
        #images is a list of encoded images as strings
        images_np = np.array(images, dtype=object)
        batches.append((images_np, labels))
    return batches

def infer_batch(client, batch):
    images_np, labels = batch
    inputs = grpcclient.InferInput("x", [len(images_np)], datatype="BYTES")
    inputs.set_data_from_numpy(images_np)

    try:
        detection_response = client.infer(model_name="simple_ensemble", inputs=[inputs])
        predictions = detection_response.as_numpy('classifier')
        return predictions, labels.numpy()
    except Exception as exc:
        print(f"Exception during inference: {exc}")
        return None, None
```

However this code doesnt work with the dali pipeline config file from the example:
https://developer.nvidia.com/blog/accelerating-inference-with-triton-inference-server-and-dali/
```
max_batch_size: 256
input [
  {
    name: "DALI_INPUT_0"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  }
]
```

because triton is expecting input with a shape [-1, -1] but its getting data in the format [ -1 ]. 

`unexpected shape for input 'x' for model 'simple_ensemble'. Expected [-1,-1], got [4].`

What would be the correct way to format the data on the client side?

**Comment by szalpal** [comment]
@Skier23 ,

could you attach a configuration for `simple_ensemble` model?

**Comment by szalpal** [comment]
```
max_batch_size: 64
input [
  {
    name: "x"
    data_type: TYPE_UINT8  # Encoded images are sent as strings
    dims: [ -1 ]
  }
]
```

I believe this part of the config is the problem. The `dims: [-1]` specifies the shape of the input sample. Additionally, the `max_batch_size` option determines, that the batching is used, therefore Triton expects that the input will have 2 dimensions: `[batch, sample]`. The error message points out, that you're passing one-dimensional input. Would you mind double-checking this?

**Comment by banasraf** [comment]
> In a productionalized environment (as I'd classify DALI with Triton), you wouldn't usually have the same input sizes for all the images.

That's true, but when you compose a batch to be sent to Triton as a single request you have the access to all the images that you want to send, so you can pad them to the size of the biggest one. 
And the requirement of uniform size applies only to images sent in a single batch, so there's no need to track any size in between the requests.

**Comment by banasraf** [comment]
You could try different options and compare them because cost of specific setups might depend on you environment. 

Option 3 would be the one that we usually propose.
Generally, encoding images (e.g. to jpegs) reduces their size dramatically, so usually sending decoded data adds a lot of communication overhead. But, if you resize them down to dimensions that are much smaller than the original image, they might not impose that much of overhead. 

I would rather avoid decoding, encoding and then decoding it again on the server. This is a costly operation that tends to dominate the cost of the whole preprocessing pipeline, so multiplying this work might be too expensive.
