### ISSUE TITLE
DALI Pipeline with GPU input broken with latest version.

### ISSUE THREAD

**Issue by omerbenamram** [triton-inference-server/dali_backend#38]
Hello,

We are using multiple DALI backend steps in an ensemble pipeline.

We are using `master` version of `dali_backend` compiled from source inside a docker image  of tritonserver 21.02.

There is a DALI pipeline in the middle of the ensemble - that receives GPU input.

The pipeline will segfault on any input.

I've installed LLDB and compiled a debug instance of `dali_backend`.

The issue stems from the addition of #16 .

```
(lldb) bt
* thread #15, name = 'tritonserver', stop reason = signal SIGSEGV: address access protected (fault address: 0x7ffe56096000)
    frame #0: 0x00007ffff69e96c3 libc.so.6`___lldb_unnamed_symbol1092$$libc.so.6 + 83
  * frame #1: 0x00007fff88368d15 libtriton_dali.so`void triton::backend::dali::detail::copy<triton::backend::dali::StorageCpu>(dst=0x00007ffa90003580, src=0x00007ffe56096000, count=2764800) at io_descriptor.h:78:9
    frame #2: 0x00007fff8836558e libtriton_dali.so`triton::backend::dali::IODescriptor<char, triton::backend::dali::StorageCpu, true>::append(this=0x00007ffa90003500, buffer="", size=2764800) at io_descriptor.h:160:33
    frame #3: 0x00007fff88357049 libtriton_dali.so`triton::backend::dali::detail::GenerateInputs(request=0x00007ffb640038d0) at dali_backend.h:148:24
    frame #4: 0x00007fff88357ac4 libtriton_dali.so`triton::backend::dali::detail::ProcessRequest(response=0x00007ffa90002fb0, request=0x00007ffb640038d0, executor=0x00007ffdf0006d90) at dali_backend.h:206:44
    frame #5: 0x00007fff8835b483 libtriton_dali.so`triton::backend::dali::TRITONBACKEND_ModelInstanceExecute(instance=0x00007ffdf0010340, reqs=0x00007ffa90000f30, request_count=1) at dali_backend.cc:423:71
```

Since `GenerateInputs` is templated over `IoDescr<true>` - It is only ever implemeted for `StorageBackend=Cpu`.

The code seems to assume that at https://github.com/triton-inference-server/dali_backend/blob/main/src/dali_backend.h#L129, but this is overridden by triton in https://github.com/triton-inference-server/dali_backend/blob/main/src/dali_backend.h#L133 with possibly an Input with `device_type == GPU`.

However when a GPU input is present, because of the templating `memcpy` will be called with a GPU pointer, and crash the pipeline.

Since this information is only provided to `dali_backend` at runtime, we need some runtime checks to correctly choose between GPU or CPU storages, instead of templating.

Thanks!

**Comment by banasraf** [comment]
Hello, @omerbenamram 
Yes, there is definitely a problem with that. We didn't focus on supporting GPU inputs as it's not the most popular use-case for DALI, but we definitely shouldn't end with segfault when the GPU input is provided. 

Adding support for GPU input is the next feature that we will be working on but before that I will probably add some check to generate a meaningful error. Thanks for reporting!
