### ISSUE TITLE
resnet50_trt example doesn't work based on README instructions

### ISSUE THREAD

**Issue by austingg** [triton-inference-server/dali_backend#44]
resnet50_trt example doesn't work based on README instructions.  

first, there is a typo parser -> perser in `client.py` 

second, load_image func does not return result. [problem position](https://github.com/triton-inference-server/dali_backend/blob/main/docs/examples/resnet50_trt/client.py#L38), so there is no data send to triton inference server 😞

**Comment by szalpal** [comment]
Hi @austingg !
Muchas gracias, very nice catch. I've submitted a PR with the fix (#45). Will work after merging.
