### ISSUE TITLE
Can dila be used to process the output of the network? Such as nms.

### ISSUE THREAD

**Issue by scuizhibin** [triton-inference-server/dali_backend#48]

**Comment by szalpal** [comment]
Hello @scuizhibin !
If I understood you correctly, you would like to process an image with an object detection network and then process the same image with DALI, e.g. crop to extract the object itself.

There's no problem with this kind of processing. All you need to do is to put together a model ensemble, where the first model in the ensemble would be the object detection network, followed by DALI model. As always, the input to DALI pipeline should be a `fn.external_source` operator, which `name` parameter should match the name assigned to input in `config.pbtxt` file of the model.

**Comment by ShiyangZhang** [comment]
`process an image with an object detection network and then process the same image with DALI, e.g. crop to extract the object itself.`
hope there are some examples

**Comment by banasraf** [comment]
Hi @ShiyangZhang 
Currently we don't have any examples of DALI used of post-processing in Triton. 
Although, configuring Triton ensemble with DALI as post-processing part shouldn't be much different from the configuring it with DALI for pre-processing. We have examples of the latter (e.g.  [Inception model](https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/inception_ensemble)).
If you encounter any specific problem setting up such use-case, I will be happy to help.

**Comment by ShiyangZhang** [comment]
> Hi @ShiyangZhang
> Currently we don't have any examples of DALI used of post-processing in Triton.
> Although, configuring Triton ensemble with DALI as post-processing part shouldn't be much different from the configuring it with DALI for pre-processing. We have examples of the latter (e.g. [Inception model](https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/inception_ensemble)).
> If you encounter any specific problem setting up such use-case, I will be happy to help.

Thanks for your reply!
In fact, I`m wondering if I can use it instand of deepstream. More over, I hope there is only one pipeline, own all models.  
[https://github.com/NVIDIA-AI-IOT/deepstream_reference_apps/blob/master/back-to-back-detectors/README.md](here is an example)

**Comment by JanuszL** [comment]
Hi @ShiyangZhang,

I think this question is more related to how to do the inference using TRITON instead of DeepStream, than how to use the DALI backend.
DALI backend is used to accelerate data processing, and from what I see in the mentioned example the only data processing defined explicitly is video decoding. In the case of the DALI backend it is not possible to decode a stream of data. What I recommend doing is to check [DeepStream with TRITON guide](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_Quickstart.html#deepstream-triton-inference-server-usage-guidelines).
