### ISSUE TITLE
Jetson Jetpack Support

### ISSUE THREAD

**Issue by ioangatop** [triton-inference-server/dali_backend#80]
Hi! I would like to ask if or there is plan for Dali backend to be support aarch64 architectures (ie Jetson devices etc). Thanks!

**Comment by szalpal** [comment]
Hello @ioangatop !

Yes, aarch64 is on our priority list, however we need to correlate it with Triton's support. So far I believe you should be able to build DALI Backend together with Triton for ARM, but to be honest we didn't test it. Did you have any particular problems using DALI Backend on aarch64?
