### ISSUE TITLE
DALI on Jetson Devices

### ISSUE THREAD

**Issue by sarperkilic** [triton-inference-server/dali_backend#95]
Hello everyone,

I have Jetson Nano and Xavier.

My purpose is that using DALI in Triton inference server pipeline as a preprocess model. I installed Triton Inference DALI backend, but when I run the example DALI script(https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/inception_ensemble), I got an error that 'Import error: No module named nvidia.dali' for import nvidia.dali as dali line.

How can I add DALI to my Triton server ensemble model pipeline as a preprocess model?

Thanks for any help

**Comment by szalpal** [comment]
Hello @sarperkilic !

Does this error happen when you are running `setup_inception_ensemble.sh` script?

**Comment by JanuszL** [comment]
Hi @sarperkilic,

How did you build the Triton Inference DALI backend and installed DALI itself? There is no DALI prebuild binary available for Nano/Xavier although you can build it on your own using [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#cross-compiling-for-aarch64-jetson-linux-docker).

**Comment by szalpal** [comment]
Closing on no response. Please reopen if it's necessary.
