### ISSUE TITLE
example resnet50_trt doesn't work when following the steps of "Quick setup"

### ISSUE THREAD

**Issue by jackyh** [triton-inference-server/dali_backend#96]
When I try to run the example of resnet50_trt following the steps of "https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/resnet50_trt", it reports the error:

root@d092a933a2c1:/workspace# python serialize_dali_pipeline.py --save ./model_repository/dali/1/model.dali
Traceback (most recent call last):
  File "serialize_dali_pipeline.py", line 34, in <module>
    @dali.pipeline_def(batch_size=256, num_threads=4, device_id=0)
AttributeError: module 'nvidia.dali' has no attribute 'pipeline_def'

looks like some version issue? How to solve this?

**Comment by szalpal** [comment]
@jackyh ,

Thank you for reporting this issue! I linked the PR which fixes it.
